<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GlobalSectionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('global_sections')->truncate();

        DB::Table('global_sections')->insert([
            [
                'meta_key'  =>  'header_logo',
                'meta_value'    =>  'front/img/logo.svg',
                'type'         => 'file',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),

            ],
            [
                'meta_key' =>'favicon_icon',
                'meta_value'    =>'front/img/icon.svg',
                'type'         =>'file',
                'page_name' => 'header',
                'lang_id'     =>'1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key' =>'favicon_icon',
                'meta_value'    =>'front/img/icon.svg',
                'type'         =>'file',
                'page_name' => 'header',
                'lang_id'     =>'2',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'header_search_placeholder',
                'meta_value'    =>  'Enter a product, category, or what you’d like to compare...',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'login_btn_lable',
                'meta_value'    =>  'Login',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'sign_up_btn_lable',
                'meta_value'    =>  'Sign Up',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'sign_out_btn_lable',
                'meta_value'    =>  'Sign Out',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'exclusive',
                'meta_value'    =>  'Exclusive',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'categories',
                'meta_value'    =>  'Categories',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'top_rated_product',
                'meta_value'    =>  'Top Rated Product',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'expert_guide',
                'meta_value'    =>  'Expert Guide',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],
            [
                'meta_key'  =>  'help_center',
                'meta_value'    =>  'Help Center',
                'type'         => 'text',
                'page_name' => 'header',
                'lang_id'     =>  '1',
                'created_at'    =>  now(),
                'updated_at'    =>  now(),
            ],

                [
                    'meta_key' => 'meta_home_title',
                    'meta_value' => 'Here is meta title heading',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'Meta_home_description',
                    'meta_value' => 'Here is meta title description Get free, unbiased product comparisons, read real customer reviews, and',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
    
                [
                    'meta_key' => 'header_title',
                    'meta_value' => 'Find the Best Deals and Save on Your Next Purchase!',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'header_description',
                    'meta_value' => 'Get free, unbiased product comparisons, read real customer reviews, and',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'header_background_img',
                    'meta_value' => 'front/img/bnnr-bg.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'header_img',
                    'meta_value' => 'front/img/banner_image.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'placeholder_text',
                    'meta_value' => 'Enter a product, category, or what you’d like to compare...',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'trusted_brands_text',
                    'meta_value' => 'Trusted Brands, Unbeatable Choices',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'trusted_brands_img',
                    'meta_value' => 'front/img/marq-img1.svg',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'most_popular',
                    'meta_value' => 'Most Popular',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'campare_business',
                    'meta_value' => 'Compare Business Software',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'visit_website',
                    'meta_value' => 'visit website',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'exclusive_deals',
                    'meta_value' => 'Exclusive deals',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'all_exclusive',
                    'meta_value' => 'All Exclusive deals',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'get_this_deal',
                    'meta_value' => 'Get This Deal',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'ai_section_left_img',
                    'meta_value' => 'front/img/right-tool-vector1.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'ai_section_right_img',
                    'meta_value' => 'front/img/right-tool-vector2.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
    
    
                ],
                [
                    'meta_key' => 'ai_title',
                    'meta_value' => 'AI-Powered Smart Search',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'ai_description',
                    'meta_value' => 'Quickly discover and compare the best products with our AI-powered search, designed to match your specific needs and preferences.',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'ai_placeholder',
                    'meta_value' => 'Enter a product, category, or what you’d like to compare...',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'ai_send_img',
                    'meta_value' => 'front/img/btn-img.svg',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'top_product',
                    'meta_value' => 'Top Rated Products',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'all_top_product',
                    'meta_value' => 'All Top-Rated Products',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'latest_reviews',
                    'meta_value' => 'Latest Reviews',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'write_review',
                    'meta_value' => 'Write a Review',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'review_section_right_img',
                    'meta_value' => 'front/img/right-tool-vector1.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'review_section_left_img',
                    'meta_value' => 'front/img/right-tool-vector2.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'read_article',
                    'meta_value' => 'Read Our Articles',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'view_all_article',
                    'meta_value' => 'View All Articles',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'find_tool',
                    'meta_value' => 'Find the Right Tool',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'find_tool_left_img',
                    'meta_value' => 'front/img/right-tool-vector1.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'find_tool_right_img',
                    'meta_value' => 'front/img/right-tool-vector2.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'user_reviews_img',
                    'meta_value' => 'front/img/right-tool-img1.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'verify_user_review',
                    'meta_value' => 'Verified User Reviews',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'verify_review_description',
                    'meta_value' => 'Read real feedback from verified users to help you make the right choice.',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'price_compare_img',
                    'meta_value' => 'front/img/right-tool-img2.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'feature_price',
                    'meta_value' => 'Feature and Price Comparisons',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'feature_price_description',
                    'meta_value' => 'Easily compare software based on key features, pricing, and customer ratings.',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'independent_img',
                    'meta_value' => 'front/img/right-tool-img3.png',
                    'page_name' => 'home',
                    'type'         => 'file',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'independent',
                    'meta_value' => 'Independent Insights',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'independent_description',
                    'meta_value' => 'Access unbiased, data-driven research to get the most value from your software.',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'meta_key' => 'get_button_lable',
                    'meta_value' => 'Get Started',
                    'page_name' => 'home',
                    'type'         => 'text',
                    'lang_id' => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                ],

                [
                    'meta_key'  => 'footer_logo',
                    'meta_value' => 'front/img/logo.svg',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'file',
                ],
                [
                    'meta_key'  => 'facebook_icon',
                    'meta_value' => 'header_logo/1734508523_facebook.svg',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'file',
                ],
                [
                    'meta_key'  => 'instagram_icon',
                    'meta_value' => 'header_logo/1734508559_Instagram.svg',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'file',
                ],
                [
                    'meta_key'  => 'twitter_icon',
                    'meta_value' => 'header_logo/1734508611_Twitter.svg',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'file',
                ],
                [
                    'meta_key'  => 'facebook_url',
                    'meta_value' => 'https://www.facebook.com/login/',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'url',
                ],
                [
                    'meta_key'  => 'instagram_url',
                    'meta_value' => 'https://www.instagram.com/accounts/login/',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'url',
                ],
                [
                    'meta_key'  => 'twitter_url',
                    'meta_value' => 'https://x.com/i/flow/login',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'url',
                ],
                [
                    'meta_key'  => 'discover',
                    'meta_value' => 'Discover',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'categories',
                    'meta_value' => 'Categories',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'top_rated_product',
                    'meta_value' => 'Top Rated Products',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'exclusive_deal',
                    'meta_value' => 'Exclusive deals',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'company',
                    'meta_value' => 'Company',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'who_we_are',
                    'meta_value' => 'Who We Are',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'privacy_policy',
                    'meta_value' => 'Privacy Policy',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'terms_and_conditions',
                    'meta_value' => 'Terms and Conditions',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'vendors',
                    'meta_value' => 'Vendors',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'get_listed',
                    'meta_value' => 'Get Listed',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'vendor_login',
                    'meta_value' => 'Vendor Login',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'help',
                    'meta_value' => 'Help',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'expert_guides',
                    'meta_value' => 'Expert Guides',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'help_center',
                    'meta_value' => 'Help Center',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'contact',
                    'meta_value' => 'Contact',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'follow_us',
                    'meta_value' => 'Follow Us',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'facebook',
                    'meta_value' => 'Facebook',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'instagram',
                    'meta_value' => 'Instagram',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
                [
                    'meta_key'  => 'twitter',
                    'meta_value' => 'Twitter',
                    'page_name'  => 'footer',
                    'lang_id'    => '1',
                    'created_at' => now(),
                    'updated_at' => now(),
                    'type'       => 'text',
                ],
      
        ]);
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
    
    }  
}
